### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by mikemand** [liam-wiltshire/laravel-jit-loader#23]
Hi Liam,

Are you already working on Laravel 7 support? Is there anything I can do to help you?

**Comment by davidjr82** [comment]
I have submitted the PR #24 to add Laravel 7 support. Brief testing in a personal project and it works as 0.5.0 (Laravel 6 version - not deep tested in a real project, but I hope that works as expected). Tests and styles passes.

CC: @liam-wiltshire

**Comment by liam-wiltshire** [comment]
Thanks - appears to work, so have merged :)
